import { Metadata } from "next";

export const DefaultMetadata: Metadata = {
  metadataBase: new URL("https://kmosha.me/"),
  title: "KmoShaX",
  description: "My name is Kareem Hossam - Software Developer ",
  applicationName: "Kmosha",
  keywords: [
    "kmosha",
    "React",
    "developer",
    "frontend",
    "nextjs",
    "react",
    "frontend developer",
    "frontend engineer",
    "creative",
    "creative developer",
    "creative engineer",
    "tech",
    "software",
    "software developer",
    "portfolio",
    "frontend developer portfolio",
    "creative developer portfolio",
    "creative engineer portfolio",
    "software developer portfolio",
    "frontend engineer portfolio",
  ],
  openGraph: {
    title: "Kmosha's Portfolio",
    description: "My name is Kareem Hossam - Sineor Full-Stack Developer",
    url: "https://www.eldoraui.site/",
    images: [
      {
        url: "./public/metadata.jpg",
        width: 1200,
        height: 630,
        alt: "Portfolio - KmoSha",
      },
    ],
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "portfolio",
};
