import { ProjectProps } from "@/types/works";
import {
  SiNextui,
  SiNextdotjs,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiWebgl,
  SiHtml5,
  SiCss3,
} from "react-icons/si";

export const projects: ProjectProps[] = [
  {
    id: 0,
    name: "Idraak Platform",
    description:
      "Online learning platform based on exams and questions learning",
    technologies: [SiTypescript, SiReact, SiNextdotjs, SiTailwindcss],
    techNames: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
    techLinks: [
      "https://www.typescriptlang.org/",
      "https://reactjs.org/",
      "https://nextjs.org/",
      "https://tailwindcss.com/",
    ],
    demo: "https://idraak.vercel.app",
    image: "/projects/idraak.jpg",
    available: true,
  },
  {
    id: 1,
    name: "Ridz Studio",
    description: "Graphics Design Studio Based on website..",
    technologies: [SiTypescript, SiReact, SiNextdotjs, SiTailwindcss, SiNextui],
    techNames: ["TypeScript", "React", "Next.js", "Tailwind CSS", "NextUI"],
    techLinks: [
      "https://www.typescriptlang.org/",
      "https://reactjs.org/",
      "https://nextjs.org/",
      "https://tailwindcss.com/",
      "https://nextui.org/",
    ],
    demo: "https://ridz-platform.vercel.app/",
    image: "/projects/ridz.png",
    available: true,
  },
  {
    id: 4,
    name: "Yousef Portfolio",
    description: "Video editor, Yousef Elgamasy portfolio.",
    technologies: [SiTypescript, SiReact, SiNextdotjs, SiTailwindcss],
    techNames: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
    techLinks: [
      "https://www.typescriptlang.org/",
      "https://reactjs.org/",
      "https://nextjs.org/",
      "https://tailwindcss.com/",
    ],
    demo: "https://yousef-visuals.art/",
    image: "/projects/yousef.png",
    available: true,
  },
  {
    id: 3,
    name: "Killua Portfolio",
    description: "Killua Zoldyck fan portfolio based on WebGL and Three.js.",
    technologies: [SiHtml5, SiCss3, SiWebgl],
    techNames: ["HTML5", "CSS3", "WebGL"],
    techLinks: [
      "https://www.learn-html.org/",
      "https://learn-css.org/",
      "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API",
    ],
    demo: "https://srour-topg.github.io/Killua-portfolio/project%202/",
    image: "/projects/kilua.jpg",
    available: true,
  },

  {
    id: 2,
    name: "Originaa website",
    description: "Minercraft addons list for youtuber named originaa.",
    technologies: [SiTypescript, SiReact, SiNextdotjs, SiTailwindcss, SiNextui],
    techNames: ["TypeScript", "React", "Next.js", "Tailwind CSS", "NextUI"],
    techLinks: [
      "https://www.typescriptlang.org/",
      "https://reactjs.org/",
      "https://nextjs.org/",
      "https://tailwindcss.com/",
      "https://nextui.org/",
    ],
    demo: "https://originaa.net/",
    image: "/projects/originaa.jpeg",
    available: true,
  },
];
